name = "cloudnative-portfolio"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "cloudnative-portfolio"
route = "cloudnative-portfolio.pages.dev/*"

[env.preview]
name = "cloudnative-portfolio-preview"

# Build configuration
[build]
command = "npm run build"
cwd = ""
watch_dir = "."

[build.upload]
format = "modules"
dir = "dist"
main = "./index.html"

# Environment variables (these will be set in Cloudflare dashboard)
[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"

# Pages configuration
[pages]
# Build output directory
build_output_dir = "dist"

# Build command
build_command = "make build"

# Root directory
root_dir = "."

# Environment variables for build
[pages.env_vars]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"

# Custom headers for security and performance
[[pages.headers]]
for = "/*"
[pages.headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[pages.headers]]
for = "/*.html"
[pages.headers.values]
Cache-Control = "public, max-age=300"

[[pages.headers]]
for = "/assets/*"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.css"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.js"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.png"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.jpg"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.jpeg"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[pages.headers]]
for = "/*.webp"
[pages.headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA behavior
[[pages.redirects]]
from = "/home"
to = "/"
status = 301

[[pages.redirects]]
from = "/portfolio"
to = "/"
status = 301

# 404 handling
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200

# Development settings
[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"

# Miniflare settings for local development
[miniflare]
upstream = "https://cloudnative-portfolio.pages.dev"
watch = true
update_check = false

# KV namespaces (if needed for future features)
# [[kv_namespaces]]
# binding = "PORTFOLIO_KV"
# id = "your-kv-namespace-id"

# R2 buckets (if needed for image storage)
# [[r2_buckets]]
# binding = "PORTFOLIO_IMAGES"
# bucket_name = "cloudnative-portfolio-images"

# Analytics (optional)
[analytics]
enabled = true
