name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi

    - name: Build site
      run: |
        if [ -f package.json ]; then
          npm run build
        else
          echo "Static HTML site - no build needed"
          mkdir -p dist
          cp -r * dist/ || true
          # Remove .git and other unnecessary files from dist
          rm -rf dist/.git dist/.github dist/node_modules dist/dist 2>/dev/null || true
        fi

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cloudnative-portfolio
        directory: dist
        # Optional: Use specific branch for deployment
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Status
      if: success()
      run: |
        echo "🚀 Successfully deployed to Cloudflare Pages!"
        echo "Your site should be available at: https://cloudnative-portfolio.pages.dev"
